CREATE SCHEMA sebrae_agro;

drop table if exists sebrae_agro.tbl_fala_sebrae;

create table sebrae_agro.tbl_fala_sebrae(
    cod_fala_sebrae bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    ds_cpf varchar(14),
    ds_titulo varchar(800),
    ds_mensagem varchar(3000)
);

drop table if exists sebrae_agro.tbl_atividade;

create table sebrae_agro.tbl_atividade(
    cod_atividade bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    nome_atividade varchar(30) not null,
    descriacao_atividade varchar(800) not null,
    TYPE_STATUS char(20)
);

drop table if exists sebrae_agro.tbl_propriedade;

create table sebrae_agro.tbl_propriedade(
    cod_propriedade bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    cpf varchar(11) not null,
    nome varchar(800) not null,
    municipio varchar(800) not null,
    localizacao_json varchar(800) not null
);

drop table if exists sebrae_agro.TB_UF;

create table sebrae_agro.TB_UF(
    COD_UF bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    DS_NOME varchar(40) not null,
    DS_SIGLA varchar(2) not null
);

drop table if exists sebrae_agro.tbl_noticias;

create table sebrae_agro.tbl_noticias(
    cod_noticia bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    ds_titulo varchar(256),
    ds_mensagem varchar(3000),
    ds_titulo_botao varchar(256),
    ds_link_botao varchar(256),
    ds_autor varchar(256),
    dt_publicacao date,
    TYPE_STATUS char(20),
    ds_foto BYTEA,
    ds_tipo_imagem varchar(200)
);

drop table if exists sebrae_agro.TB_USUARIO;

create table sebrae_agro.TB_USUARIO(
    COD_USUARIO bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    DS_CPF varchar(255),
    DS_LOGIN varchar(255),
    DS_NOME varchar(255),
    BO_NOT_PUSH bool
);

drop table if exists sebrae_agro.TB_PUSH_NOTIFICATION;

create table sebrae_agro.TB_PUSH_NOTIFICATION(
    COD_PUSH_NOTIFICATION bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    DT_ALTERACAO date null,
    DT_CRIACAO date not null,
    DS_TITULO varchar(255) not null,
    DS_MENSAGEM varchar(1000) not null,
    DS_MENSAGEM_ID varchar(20) null,
    DT_NOTIFICACAO date not null,
    ST_SITUACAO varchar(20) not null,
    COD_UF bigint null,
    foreign key (COD_UF) references sebrae_agro.TB_UF (COD_UF)
);

drop table if exists sebrae_agro.tbl_praga;

create table sebrae_agro.tbl_praga(
    cod_praga bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    ds_titulo varchar(256),
    ds_mensagem varchar(3000),
    ds_foto BYTEA,
    ds_tipo_imagem varchar(200)
);

drop table if exists sebrae_agro.tbl_praga_atividade;

create table sebrae_agro.tbl_praga_atividade(
    cod_praga bigint,
    cod_atividade bigint,
    foreign key (cod_praga) references sebrae_agro.tbl_praga(cod_praga),
    foreign key (cod_atividade) references sebrae_agro.tbl_atividade(cod_atividade)
);

drop table if exists sebrae_agro.tbl_praga_ufs;

create table sebrae_agro.tbl_praga_ufs(
    cod_praga bigint,
    cod_uf bigint,
    foreign key (cod_praga) references sebrae_agro.tbl_praga(cod_praga),
    foreign key (cod_uf) references sebrae_agro.TB_UF(COD_UF)
);

drop table if exists sebrae_agro.tbl_noticias_ufs;

create table sebrae_agro.tbl_noticias_ufs(
    cod_noticia bigint,
    cod_uf bigint,
    foreign key (cod_noticia) references sebrae_agro.tbl_noticias(cod_noticia),
    foreign key (cod_uf) references sebrae_agro.TB_UF(COD_UF)
);

drop table if exists sebrae_agro.tbl_propriedade_atividade;

create table sebrae_agro.tbl_propriedade_atividade(
    cod_propriedade bigint,
    cod_atividade bigint,
    foreign key (cod_propriedade) references sebrae_agro.tbl_propriedade(cod_propriedade),
    foreign key (cod_atividade) references sebrae_agro.tbl_atividade(cod_atividade)
);

drop table if exists sebrae_agro.tbl_propriedade_ufs;

create table sebrae_agro.tbl_propriedade_ufs(
    cod_propriedade bigint,
    cod_uf bigint,
    foreign key (cod_propriedade) references sebrae_agro.tbl_propriedade(cod_propriedade),
    foreign key (cod_uf) references sebrae_agro.TB_UF(COD_UF)
);

drop table if exists sebrae_agro.tbl_noticias_atividade;

create table sebrae_agro.tbl_noticias_atividade(
    cod_noticia bigint,
    cod_atividade bigint,
    foreign key (cod_noticia) references sebrae_agro.tbl_noticias(cod_noticia),
    foreign key (cod_atividade) references sebrae_agro.tbl_atividade(cod_atividade)
);

drop table if exists sebrae_agro.tbl_push_atividade;

create table sebrae_agro.tbl_push_atividade(
    COD_PUSH_NOTIFICATION bigint,
    cod_atividade bigint,
    foreign key (COD_PUSH_NOTIFICATION) references sebrae_agro.TB_PUSH_NOTIFICATION(COD_PUSH_NOTIFICATION),
    foreign key (cod_atividade) references sebrae_agro.tbl_atividade(cod_atividade)
);

drop table if exists sebrae_agro.tbl_push_ufs;

create table sebrae_agro.tbl_push_ufs(
    COD_PUSH_NOTIFICATION bigint,
    cod_uf bigint,
    foreign key (COD_PUSH_NOTIFICATION) references sebrae_agro.TB_PUSH_NOTIFICATION(COD_PUSH_NOTIFICATION),
    foreign key (cod_uf) references sebrae_agro.TB_UF(COD_UF)
);