insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (12,'AC','Acre');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (27,'AL','Alagoas');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (13,'AM','Amazonas');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (16,'AP','Amapá');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (29,'BA','Bahia');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (23,'CE','Ceará');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (53,'DF','Distrito Federal');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (32,'ES','Espírito Santo');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (52,'GO','Goiás');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (21,'MA','Maranhão');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (31,'MG','Minas Gerais');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (50,'MS','Mato Grosso do Sul');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (51,'MT','Mato Grosso');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (15,'PA','Pará');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (25,'PB','Paraíba');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (26,'PE','Pernambuco');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (22,'PI','Piauí');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (41,'PR','Paraná');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (33,'RJ','Rio de Janeiro');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (24,'RN','Rio Grande do Norte');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (11,'RO','Rondônia');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (14,'RR','Roraima');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (43,'RS','Rio Grande do Sul');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (42,'SC','Santa Catarina');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (28,'SE','Sergipe');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (35,'SP','São Paulo');
insert into sebrae_agro.TB_UF (COD_UF, DS_SIGLA, DS_NOME) values (17,'TO','Tocantins');

insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Cana-de-açúcar', 'Cana-de-açúcar', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Fruticultura', 'Fruticultura', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Soja', 'Grãos', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Milho', 'Grãos', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Sorgo', 'Grãos', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Trigo', 'Grãos', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Arroz', 'Grãos', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Feijão', 'Grãos', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Mandiocultura', 'Horticultura', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Pastagem', 'Pastagem', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Apicultura', 'Pecuária', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Caprinocultura', 'Pecuária', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Gado de Corte', 'Pecuária', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Gado de Leite', 'Pecuária', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Ovinocultura', 'Pecuária', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Piscicultura', 'Pecuária', 'APROVADO');
insert into sebrae_agro.tbl_atividade (nome_atividade, descriacao_atividade, TYPE_STATUS) values ('Silvicultura', 'Silvicultura', 'APROVADO');
