drop table if exists sebrae_agro.tbl_lista_pragas;

create table sebrae_agro.tbl_lista_pragas(
    cod_lista_pragas bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    ds_atividade varchar(256),
    ds_cultura varchar(256),
    ds_nome varchar(256),
    TYPE_STATUS char(20)
);