drop table if exists sebrae_agro.tbl_indicador;

create table sebrae_agro.tbl_indicador(
    COD_INDICADOR bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    TX_NOME varchar(255) not null,
    TX_UNIDADE_MEDIDA varchar(255) not null,
    TX_FREQUENCIA_MENSURACAO varchar(255) not null,
    TX_FORMULA varchar(255) not null,
    TX_PADRAO varchar(255) not null,
    COD_USUARIO bigint,
    foreign key (COD_USUARIO) references sebrae_agro.TB_USUARIO (COD_USUARIO)
);

drop table if exists sebrae_agro.tbl_indicador_atividade;
create table sebrae_agro.tbl_indicador_atividade(
    COD_INDICADOR bigint,
    COD_ATIVIDADE bigint,
    foreign key (COD_INDICADOR) references sebrae_agro.tbl_indicador(COD_INDICADOR),
    foreign key (COD_ATIVIDADE) references sebrae_agro.tbl_atividade(COD_ATIVIDADE)
);

drop table if exists sebrae_agro.tbl_variavel;
create table sebrae_agro.tbl_variavel(
    COD_VARIAVEL bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    TX_NOME varchar(255) not null,
    TX_UNIDADE_MEDIDA varchar(255) not null,
    TX_FREQUENCIA_MENSURACAO varchar(255) not null,
    TX_FORMULARIO varchar(255) not null,
    COD_USUARIO bigint,
    foreign key (COD_USUARIO) references sebrae_agro.TB_USUARIO (COD_USUARIO)
);

drop table if exists sebrae_agro.tbl_variavel_atividade;
create table sebrae_agro.tbl_variavel_atividade(
    COD_VARIAVEL bigint,
    COD_ATIVIDADE bigint,
    foreign key (COD_VARIAVEL) references sebrae_agro.tbl_variavel(COD_VARIAVEL),
    foreign key (COD_ATIVIDADE) references sebrae_agro.tbl_atividade(COD_ATIVIDADE)
);